### ISSUE TITLE
Node commissioning failing with playbook error - site.yml/cleanup.yml not found

### ISSUE THREAD

**Issue by rkharya** [contiv/ansible#193]
UCP - 1.1.0
Docker - 1.11.0
Ansible/Cluster - Latest, clonned on 05/13

While commissioning service-master host, commissioning task is failing with below error -

[cluster-admin@Docker-1 ansible]$ clusterctl node c Docker-2-FLM19379EUC --host-group=service-master

[cluster-admin@Docker-1 ansible]$ clusterctl job get active
FATA[0000] Request URL: info/job/active Request Body: <nil> Response status: "500 Internal Server Error". Response body: info for "active" job doesn't exist

[cluster-admin@Docker-1 ansible]$ clusterctl job get last
{
    "task": "github.com/contiv/cluster/management/src/clusterm/manager.(*commissionEvent).(github.com/contiv/cluster/management/src/clusterm/manager.configureOrCleanupOnErrorRunner)-fm",
    "status": "Errored",
    "error": "exit status 1",
    "logs": [
        "ERROR! the playbook: /vagrant/vendor/ansible/site.yml could not be found",
        "ERROR! the playbook: /vagrant/vendor/ansible/cleanup.yml could not be found",
        ""
    ]
}
[cluster-admin@Docker-1 ansible]$

**Comment by rkharya** [comment]
[journalctl-clusterm.txt](https://github.com/contiv/ansible/files/263321/journalctl-clusterm.txt)

**Comment by mapuri** [comment]
@rkharya the cluster config got changed as part of https://github.com/contiv/cluster/pull/132 . 

The playbook location now needs to be specified as `playbook_location` instead of `playbook-location` in the config file. This was to make JSON consistent before hitting the first milestone for clusterm.

You can update the config file and restart clusterm and it shall work. Feel free to reopen or file another issue if it still doesn't work for you.

**Comment by rkharya** [comment]
[cluster-admin@Docker-1 ansible]$ cat /etc/default/clusterm/clusterm.conf
{
    "ansible": {
        "playbook_location": "/home/cluster-admin/ansible/",
        "user": "cluster-admin",
        "priv_key_file": "/home/cluster-admin/.ssh/id_rsa"
    }
}

Its using 'playbook_location' only...
