### ISSUE TITLE
Need to bring in capabilities to reinstall/restart services

### ISSUE THREAD

**Issue by dvavili** [contiv/ansible#42]
Encountered many issues while trying to re-run playbook on a node because of older version or after change in environment variables. Need a mechanism to identify if the services running on a node are of older version/older configuration and reinstall/restart the services as necessary.

**Comment by jainvipin** [comment]
ping @erikh, @mapuri, @jojimt 

I agree with @DivyaVavili - having a way to clean-up an be able to restart will come very handy when we are in a situation that is not-repairable.

We have a choice of doing this either with ansible or a non-ansible script, as in https://github.com/contiv/netplugin/scripts/python/cleanup.py, and startPlugin.py scripts do.

Advantages of doing it in ansible:
- consistent ways of starting/restarting/stopping services
- once place for all changes
  Advantages of doing it outside:
- Assuming we'd never need this in production, this is needed primarily for stabilization cycle.

We must also answer, if this were to happen in a production environment, what is our answer? How can it be started cleanly?

**Comment by erikh** [comment]
Ansible should be used to configure the system, systemd should be used to manage the services.

More direct, the python script needs to go.

**Comment by mapuri** [comment]
In general, I agree that ansible can be used to configure and cleanup services with each role/specific cleanup taken care within that scope.

I am tracking the cleanup of services with #38 . I am hoping to setup/organize our roles to perform  respective cleanups with this change.

I am targeting a production use case though i.e. a node is commissioned to start up services correclty and a node is decommissioned to cleanup services. I am not sure if this will cover dev/test usecases but may be we can need to a step at a time since we will be introducing a new workflow i.e. in short-term a restart might imply run a decommission playbook followed by commission playbook.

**Comment by erikh** [comment]
Sure; not suggesting it needs to happen overnight, but we should have a strategy to get rid of these ad-hoc tools that aren't resilient. The tool, which I have used before, is not very respecting of errors nor does it handle input correctly. Ansible will. That was the meat of my comment.

**Comment by mapuri** [comment]
great. I think I am on same page here then. Hopefully I will have something to show and try out soon for you folks.

**Comment by mapuri** [comment]
#44 addresses the service cleanup. Let's track missing items through separate issues
